package com.gagoo.thiscoding.domain.mock;

import com.gagoo.thiscoding.domain.mongo.code.domain.Code;
import com.gagoo.thiscoding.domain.mongo.code.service.port.CodeRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.support.PageableExecutionUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeCodeRepository implements CodeRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Code> data = new ArrayList<>();

    @Override
    public Code save(Code code) {
        if (code.getId() == null || code.getId().isBlank()) {
            Code newCode = Code.builder()
                    .id(generatedTestId())
                    .roomId(code.getRoomId())
                    .writerId(code.getWriterId())
                    .fileName(code.getFileName())
                    .value(code.getValue())
                    .saveDate(code.getSaveDate())
                    .build();

            data.add(newCode);
            return newCode;
        } else {
            data.removeIf(item -> item.getId().equals(code.getId()));
            data.add(code);
            return code;
        }
    }

    @Override
    public boolean existsByRoomIdAndFileName(Long roomId, String fileName) {
        return data.stream().anyMatch(item -> item.getRoomId().equals(roomId) && item.getFileName().equals(fileName));
    }

    @Override
    public boolean existsByRoomId(Long roomId) {
        return data.stream().anyMatch(item -> item.getRoomId().equals(roomId));
    }

    @Override
    public Optional<Code> findById(String id) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public Optional<Code> findByRoomIdAndFileName(Long roomId, String fileName) {
        return data.stream().filter(item -> item.getRoomId().equals(roomId) && item.getFileName().equals(fileName)).findAny();
    }

    @Override
    public Page<Code> findByRoomId(Long roomId, Pageable pageable) {
        if (pageable.getPageSize() < 1) {
            return Page.empty(pageable);
        }

        List<Code> findRoomId = data.stream().filter(item -> item.getRoomId().equals(roomId)).toList();

        int start = (int) pageable.getOffset();
        int end = Math.min(start + pageable.getPageSize(), findRoomId.size());

        if(start >= findRoomId.size()) {
            return Page.empty(pageable);
        }

        List<Code> pageableCode = findRoomId.subList(start, end);

        return PageableExecutionUtils.getPage(
                pageableCode,
                pageable,
                findRoomId::size
        );
    }

    private String generatedTestId() {
        return "test-code-" + autoGeneratedId.incrementAndGet();
    }
}
