package com.gagoo.thiscoding.domain.mock;

import com.gagoo.thiscoding.domain.mongo.code.domain.Code;
import com.gagoo.thiscoding.domain.mongo.code.service.port.CodeRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeCodeRepository implements CodeRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Code> data = new ArrayList<>();

    @Override
    public Code save(Code code) {
        if (code.getId() == null || code.getId().isBlank()) {
            Code newCode = Code.builder()
                    .id(generatedTestId())
                    .roomId(code.getRoomId())
                    .writerId(code.getWriterId())
                    .fileName(code.getFileName())
                    .value(code.getValue())
                    .saveDate(code.getSaveDate())
                    .build();

            data.add(newCode);
            return newCode;
        } else {
            data.removeIf(item -> item.getId().equals(code.getId()));
            data.add(code);
            return code;
        }
    }

    @Override
    public boolean existsByRoomIdAndFileName(Long roomId, String fileName) {
        return data.stream().anyMatch(item -> item.getRoomId().equals(roomId) && item.getFileName().equals(fileName));
    }

    @Override
    public Optional<Code> findById(String id) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public Optional<Code> findByRoomIdAndFileName(Long roomId, String fileName) {
        return data.stream().filter(item -> item.getRoomId().equals(roomId) && item.getFileName().equals(fileName)).findAny();
    }

    private String generatedTestId() {
        return "test-code-" + autoGeneratedId.incrementAndGet();
    }
}
