package com.gagoo.thiscoding.domain.mock;

import com.gagoo.thiscoding.domain.maria.manager.domain.Manager;
import com.gagoo.thiscoding.domain.maria.manager.service.port.ManagerRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;

import java.util.*;

public class FakeManagerRepository implements ManagerRepository {

    private Long autoGeneratedId = 0L;
    private final List<Manager> data = new ArrayList<>();

    @Override
    public Optional<Manager> findById(Long id) {
        return Optional.ofNullable(data.stream().filter(item -> item.getId().equals(id))
                .findAny()
                .orElseThrow(() -> new IllegalArgumentException("Manager not found with id: " + id)));

    }

    @Override
    public boolean existsById(Long id) {
        return data.stream().anyMatch(manager -> manager.getId().equals(id));
    }

    @Override
    public Page<Manager> findAll(Pageable pageable) {
        int start = (int) pageable.getOffset();
        int end = Math.min((start + pageable.getPageSize()), data.size());
        List<Manager> subList = data.subList(start, end);
        return new PageImpl<>(subList, pageable, data.size());
    }

    @Override
    public Manager save(Manager manager) {
        if (manager.getId() == null || manager.getId() == 0) {
            Manager newManager = Manager.builder()
                    .id(++autoGeneratedId)
                    .manager(manager.getManager())
                    .content(manager.getContent())
                    .category(manager.getCategory())
                    .build();
            data.add(newManager);
            return newManager;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), manager.getId()));
            data.add(manager);
            return manager;
        }
    }

    @Override
    public void deleteById(Long id) {
        data.removeIf(item -> item.getId().equals(id));
    }
}
