package com.gagoo.thiscoding.domain.mock;

import com.gagoo.thiscoding.domain.maria.reply.domain.Reply;
import com.gagoo.thiscoding.domain.maria.reply.service.dto.ReplyList;
import com.gagoo.thiscoding.domain.maria.reply.service.port.ReplyRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.support.PageableExecutionUtils;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

public class FakeReplyRepository implements ReplyRepository {

    private Long autoGeneratedId = 0L;
    private final List<Reply> data = new ArrayList<>();

    @Override
    public Reply save(Reply reply) {
        if (reply.getId() == null || reply.getId() == 0) {
            Reply savedReply = Reply.builder()
                    .id(++autoGeneratedId)
                    .qnaId(reply.getQnaId())
                    .user(reply.getUser())
                    .content(reply.getContent())
                    .parentId(reply.getParentId())
                    .isBlinded(reply.isBlinded())
                    .createDate(reply.getCreateDate())
                    .build();
            data.add(savedReply);

            return savedReply;
        } else {
            data.removeIf(item -> item.getId().equals(reply.getId()));
            data.add(reply);

            return reply;
        }
    }

    @Override
    public Optional<Reply> findById(Long id) {
        return data.stream()
                .filter(item -> item.getId().equals(id))
                .findAny();
    }

    @Override
    public Page<ReplyList> findByQnaId(String qnaId, Pageable pageable) {
        if (pageable.getPageSize() < 1) {
            return Page.empty(pageable);
        }

        List<ReplyList> findAllReply = data.stream()
                .filter(reply -> reply.getQnaId().equals(qnaId))
                .sorted(Comparator.comparing(Reply::getCreateDate).reversed())
                .map(reply -> ReplyList.builder()
                        .replyId(reply.getId())
                        .parentId(reply.getParentId())
                        .nickname(reply.getUser().getNickname())
                        .profileImage(reply.getUser().getImageUrl())
                        .content(reply.getContent())
                        .createDate(reply.getCreateDate())
                        .build())
                .collect(Collectors.toList());

        int start = (int) pageable.getOffset();
        int end = Math.min(start + pageable.getPageSize(), findAllReply.size());

        if (start >= findAllReply.size()) {
            return Page.empty(pageable);
        }

        List<ReplyList> pagedReplies = findAllReply.subList(start, end);

        return PageableExecutionUtils.getPage(
                pagedReplies,
                pageable,
                () -> (long) findAllReply.size()
        );
    }


    @Override
    public Long countByQnaId(String qnaId) {
        return data.stream().filter(item -> item.getQnaId().equals(qnaId)).count();
    }

    @Override
    public boolean existsById(Long parentId) {
        return data.stream()
                .anyMatch(reply -> reply.getParentId().equals(parentId));
    }

    @Override
    public void delete(Reply reply) {

    }
}
