package com.gagoo.thiscoding.domain.mock;

import com.gagoo.thiscoding.domain.maria.bookmark.domain.Bookmark;
import com.gagoo.thiscoding.domain.maria.bookmark.service.port.BookmarkRepository;
import org.springframework.data.domain.Pageable;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakeBookmarkRepository implements BookmarkRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Bookmark> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Bookmark save(Bookmark bookmark) {
        if(bookmark.getId() == null || bookmark.getId() == 0) {
            Bookmark newbookmark = Bookmark.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .user(bookmark.getUser())
                    .qnaId(bookmark.getQnaId())
                    .build();
            data.add(newbookmark);
            return newbookmark;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), bookmark.getId()));
            data.add(bookmark);
            return bookmark;
        }
    }

    @Override
    public Optional<Bookmark> findByQnaIdAndUserId(String qnaId, Long userId) {
        return data.stream().filter(item -> item.getQnaId().equals(qnaId) && item.getUser().equals(userId)).findFirst();
    }

    @Override
    public void deleteById(Long id) {
        data.removeIf(item -> Objects.equals(item.getId(), id));
    }

    @Override
    public boolean existsByQnaIdAndUserId(String qnaId, Long userId) {
        return data.stream()
                .anyMatch(bookmark -> bookmark.getQnaId().equals(qnaId)
                        && bookmark.getUser().equals(userId));
    }

    @Override
    public List<String> findQnaIdsByUserIdPaged(Long userId, Pageable pageable) {
        return data.stream().filter(item -> item.getUser().equals(userId)).map(Bookmark::getQnaId).collect(Collectors.toList());
    }
}
