package com.gagoo.thiscoding.domain.mock;

import com.gagoo.thiscoding.domain.maria.user.domain.User;
import com.gagoo.thiscoding.domain.maria.user.service.port.UserRepository;
import com.gagoo.thiscoding.global.exception.ErrorCode;
import com.gagoo.thiscoding.global.security.exception.UserNotFoundException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeUserRepository implements UserRepository {

    private Long autoGeneratedId = 0L;
    private final List<User> data = new ArrayList<>();

    @Override
    public User save(User user) {
        if (user.getId() == null || user.getId() == 0) {
            User saveUser = User.builder()
                    .id(++autoGeneratedId)
                    .email(user.getEmail())
                    .password(user.getPassword())
                    .nickname(user.getNickname())
                    .imageUrl(user.getImageUrl())
                    .isActivated(user.isActivated())
                    .isBanned(user.isBanned())
                    .role(user.getRole())
                    .social(user.getSocial())
                    .build();

            data.add(saveUser);
            return saveUser;
        } else {
            data.removeIf(item -> item.getId().equals(user.getId()));
            data.add(user);
            return user;
        }
    }

    @Override
    public Optional<User> findById(Long id) {
        return data.stream()
                .filter(item -> item.getId().equals(id))
                .findAny();
    }

    @Override
    public User getByEmail(String email) {
        return findByEmail(email).orElseThrow(
                () -> new UserNotFoundException(ErrorCode.USER_NOT_FOUND)
        );
    }

    @Override
    public boolean existsByEmail(String email) {
        return data.stream()
                .anyMatch(user -> user.getEmail().equals(email));
    }

    @Override
    public boolean existsByNickname(String nickname) {
        return data.stream()
                .anyMatch(user -> user.getNickname().equals(nickname));
    }

//    @Override
//    public boolean existsByUserId(Long userId) {
//        return data.stream()
//                .anyMatch(user -> user.getId().equals(userId));
//    }

    public Optional<User> findByEmail(String email) {
        return data.stream()
                .filter(user -> user.getEmail().equals(email))
                .findFirst();
    }

    @Override
    public Optional<User> findByNickname(String nickname) {
        return Optional.empty();
    }

    @Override
    public Page<User> findByNicknameContaining(String nickname, Pageable pageable) {
        return null;
    }

    @Override
    public User getByNickname(String nickname) {
        return null;
    }
}
