package com.gagoo.thiscoding.domain.mock;

import com.gagoo.thiscoding.domain.maria.usercoderoom.domain.UserCodeRoom;
import com.gagoo.thiscoding.domain.maria.usercoderoom.service.exception.UserCodeRoomNotFoundException;
import com.gagoo.thiscoding.domain.maria.usercoderoom.service.port.UserCodeRoomRepository;
import com.gagoo.thiscoding.global.exception.ErrorCode;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeUserCodeRoomRepository implements UserCodeRoomRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<UserCodeRoom> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public UserCodeRoom getById(Long codeRoomId) {
        return findById(codeRoomId).orElseThrow(
                () -> new UserCodeRoomNotFoundException(ErrorCode.USER_CODE_ROOM_NOT_FOUND)
        );
    }

    @Override
    public Optional<UserCodeRoom> findById(Long codeRoomId) {
        return data.stream().filter(item -> item.getCodeRoom().getId().equals(codeRoomId)).findAny();
    }

    @Override
    public UserCodeRoom save(UserCodeRoom userCodeRoom) {
        if (userCodeRoom.getId() == null || userCodeRoom.getId() == 0) {
            UserCodeRoom newUserCodeRoom = UserCodeRoom.builder()
                .id(autoGeneratedId.incrementAndGet())
                .user(userCodeRoom.getUser())
                .codeRoom(userCodeRoom.getCodeRoom())
                .isActivated(userCodeRoom.isActivated())
                .build();
            data.add(newUserCodeRoom);
            return newUserCodeRoom;

        } else {
            data.removeIf(item -> Objects.equals(item.getId(), userCodeRoom.getId()));
            data.add(userCodeRoom);
            return userCodeRoom;
        }
    }

    @Override
    public void deleteById(Long userCodeRoomId) {
        data.removeIf(item -> Objects.equals(item.getId(), userCodeRoomId));
    }

    @Override
    public boolean existByCodeRoomIdAndUserId(Long codeRoomId, Long userId) {
        return data.stream()
            .anyMatch(userCodeRoom -> userCodeRoom.getCodeRoom().equals(codeRoomId)
                && userCodeRoom.getUser().getId().equals(userId));
    }
}
