package com.gagoo.thiscoding.domain.mock;

import com.gagoo.thiscoding.domain.maria.like.domain.Like;
import com.gagoo.thiscoding.domain.maria.like.service.port.LikeRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeLikeRepository implements LikeRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Like> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Like save(Like like) {
        if(like.getId() == null || like.getId() == 0) {
            Like newLike = Like.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .user(like.getUser())
                    .qnaId(like.getQnaId())
                    .build();
            data.add(newLike);
            return newLike;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), like.getId()));
            data.add(like);
            return like;
        }
    }

    @Override
    public Optional<Like> findByQnaIdAndUserId(String qnaId, Long userId) {
        return data.stream().filter(item -> item.getQnaId().equals(qnaId) && item.getUser().equals(userId)).findFirst();
    }

    @Override
    public void deleteById(Long id) {
        data.removeIf(item -> Objects.equals(item.getId(), id));
    }

    @Override
    public boolean existsByQnaIdAndUserId(String qnaId, Long userId) {
        return data.stream()
                .anyMatch(like -> like.getQnaId().equals(qnaId)
                && like.getUser().equals(userId));
    }
}
