package com.gagoo.thiscoding.domain.mock;

import com.gagoo.thiscoding.domain.maria.alarm.domain.Alarm;
import com.gagoo.thiscoding.domain.maria.alarm.domain.AlarmType;
import com.gagoo.thiscoding.domain.maria.alarm.service.exception.AlarmNotFoundException;
import com.gagoo.thiscoding.domain.maria.alarm.service.port.AlarmRepository;
import com.gagoo.thiscoding.global.exception.ErrorCode;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeAlarmRepository implements AlarmRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Alarm> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Alarm getById(Long alarmId) {
        return data.stream().filter(item -> item.getId().equals(alarmId)).findAny().orElseThrow(
            () -> new AlarmNotFoundException(ErrorCode.ALARM_NOT_FOUND)
        );
    }

    @Override
    public Optional<Alarm> findById(Long alarmId) {
        return data.stream().filter(item -> item.getId().equals(alarmId)).findAny();
    }

    @Override
    public Alarm save(Alarm alarm) {
        if (alarm.getId() == null || alarm.getId() == 0) {
            alarm = Alarm.builder()
                .id(autoGeneratedId.incrementAndGet())
                .sender(alarm.getSender())
                .receiver(alarm.getReceiver())
                .targetId(alarm.getTargetId())
                .type(alarm.getType())
                .isRead(alarm.isRead())
                .createDate(alarm.getCreateDate())
                .build();
        } else {
            Long alarmId = alarm.getId();
            data.removeIf(item -> Objects.equals(item.getId(), alarmId));
        }
        data.add(alarm);
        return alarm;
    }

    @Override
    public void deleteById(Long alarmId) {
        data.removeIf(item -> Objects.equals(item.getId(), alarmId));
    }

    @Override
    public boolean existsByIdAndTypeAndTargetId(Long alarmId, AlarmType alarmType, Long targetId) {
        return data.stream()
            .anyMatch(alarm -> alarm.getId().equals(alarmId) && alarm.getType().equals(alarmType)
                && alarm.getTargetId().equals(targetId));
    }

}
