package com.gagoo.thiscoding.domain.mock;

import com.gagoo.thiscoding.domain.maria.alarm.domain.Alarm;
import com.gagoo.thiscoding.domain.maria.alarm.domain.AlarmType;
import com.gagoo.thiscoding.domain.maria.coderoom.domain.CodeRoom;
import com.gagoo.thiscoding.domain.maria.coderoom.domain.dto.InvitationCodeRoom;
import com.gagoo.thiscoding.domain.maria.coderoom.service.port.CodeRoomRepository;
import com.gagoo.thiscoding.domain.maria.user.domain.User;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.support.PageableExecutionUtils;

public class FakeCodeRoomRepository implements CodeRoomRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<CodeRoom> codeRooms = Collections.synchronizedList(new ArrayList<>());
    private final List<Alarm> alarms = Collections.synchronizedList(new ArrayList<>());
    private final List<User> users = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Page<InvitationCodeRoom> findInvitedCodeRoomsByUser(User user, Pageable pageable) {
        if (pageable.getPageSize() < 1) {
            return Page.empty(pageable);
        }

        List<Alarm> filteredAlarms = alarms.stream()
            .filter(alarm -> alarm.getReceiver().getId().equals(user.getId()) &&
                alarm.getType().equals(AlarmType.CODE))
            .collect(Collectors.toList());

        Map<Long, CodeRoom> codeRoomMap = codeRooms.stream()
            .collect(Collectors.toMap(CodeRoom::getId, room -> room));

        Map<Long, User> userMap = users.stream()
            .collect(Collectors.toMap(User::getId, userEntity -> userEntity));

        List<InvitationCodeRoom> results = filteredAlarms.stream()
            .map(alarm -> {
                CodeRoom codeRoom = codeRoomMap.get(alarm.getTargetId());
                User sender = userMap.get(alarm.getSender().getId());
                return new InvitationCodeRoom(
                    alarm.getId(),
                    codeRoom.getId(),
                    codeRoom.getTitle(),
                    codeRoom.getContent(),
                    codeRoom.getHeadCount(),
                    codeRoom.getLanguage(),
                    sender.getNickname(),
                    sender.getImageUrl()
                );
            })
            .skip(pageable.getOffset())
            .limit(pageable.getPageSize())
            .collect(Collectors.toList());

        return PageableExecutionUtils.getPage(
            results,
            pageable,
            () -> (long) filteredAlarms.size()
        );
    }

    @Override
    public Optional<CodeRoom> findByUuid(String uuid) {
        return Optional.empty();
    }

    @Override
    public Optional<CodeRoom> findById(Long id) {
        return codeRooms.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public CodeRoom save(CodeRoom codeRoom) {
        if (codeRoom.getId() == null || codeRoom.getId() == 0) {
            codeRoom = CodeRoom.builder()
                .id(autoGeneratedId.incrementAndGet())
                .uuid(codeRoom.getUuid())
                .title(codeRoom.getTitle())
                .content(codeRoom.getContent())
                .language(codeRoom.getLanguage())
                .headCount(codeRoom.getHeadCount())
                .build();
        } else {
            Long codeRoomId = codeRoom.getId();
            codeRooms.removeIf(item -> Objects.equals(item.getId(), codeRoomId));
        }
        codeRooms.add(codeRoom);
        return codeRoom;
    }

    @Override
    public void deleteById(Long id) {
        codeRooms.removeIf(item -> Objects.equals(item.getId(), id));
    }
}
