package com.gagoo.thiscoding.domain.maria.manager.mock;

import com.gagoo.thiscoding.domain.maria.manager.domain.Manager;
import com.gagoo.thiscoding.domain.maria.manager.service.port.ManagerRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeManagerRepository implements ManagerRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Manager> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Manager findById(Long id) {
        return data.stream().filter(item -> item.getId().equals(id))
                .findAny()
                .orElseThrow(() -> new IllegalArgumentException("Manager not found with id: " + id));

    }

    @Override
    public Page<Manager> findAll(Pageable pageable) {
        int start = (int) pageable.getOffset();
        int end = Math.min((start + pageable.getPageSize()), data.size());
        List<Manager> subList = data.subList(start, end);
        return new PageImpl<>(subList, pageable, data.size());
    }

    @Override
    public Manager save(Manager manager) {
        if (manager.getId() == null || manager.getId() == 0) {
            Manager newManager = Manager.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .manager(manager.getManager())
                    .content(manager.getContent())
                    .category(manager.getCategory())
                    .build();
            data.add(newManager);
            return newManager;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), manager.getId()));
            data.add(manager);
            return manager;
        }
    }

    @Override
    public void deleteById(Long id) {
        data.removeIf(item -> item.getId().equals(id));
    }
}
