name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 서브모듈 포함 레포지토리 체크아웃
        uses: actions/checkout@v3
        with:
            submodules: true
            fetch-depth: 0
            token: ${{ secrets.GH_ATK }}

      - name: JDK 설치
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Gradle 권한 설정
        run: chmod +x gradlew

      - name: 운영서버 테스트 없이 빌드
        run: ./gradlew clean build -Dspring.profiles.active=prod -x test



      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 도커 허브 로그인
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: 도커 이미지 빌드 후 푸시
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jaew0n/thiscoding:latest


      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull jaew0n/thiscoding:latest
            docker rm -f thiscoding-container || true
            docker run -d \
              --name thiscoding-container \
              --restart unless-stopped \
              -p 80:8080 \
              -v thiscoding-data:/app/data \
              -e SPRING_PROFILES_ACTIVE=prod \
              jaew0n/thiscoding:latest
            docker ps | grep thiscoding-container
