name: CI/CD Pipeline

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  test:
    name: Gradle Build Test
    runs-on: ubuntu-latest

    steps:
      - name: 서브모듈 포함 레포지토리 체크아웃
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GH_ATK }}

      - name: JDK 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 권한 설정
        run: chmod +x gradlew

      - name: Gradle 캐시 삭제
        run: ./gradlew clean --no-build-cache

      # - name: 테스트 진행
      #   run: ./gradlew test -Dspring.profiles.active=test

  deploy:
    name: Deploy Pipeline
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}

    steps:
      - name: 서브모듈 포함 레포지토리 체크아웃
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GH_ATK }}

      - name: JDK 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 권한 설정
        run: chmod +x gradlew

      - name: 운영서버 테스트 없이 빌드
        run: ./gradlew clean build -Dspring.profiles.active=prod -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 도커 허브 로그인
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: 도커 이미지 빌드 후 푸시
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-prod
          push: true
          tags: |
            jaew0n/thiscoding:latest

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull jaew0n/thiscoding:latest
            docker rm -f thiscoding-container || true
            docker run -d \
              --name thiscoding-container \
              --restart unless-stopped \
              -p 8080:8080 \
              -v thiscoding-data:/app/data \
              jaew0n/thiscoding:latest
            docker ps | grep thiscoding-container
