name: Docker Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: CI Pipeline에서 저장한 아티팩트 다운로드
        uses: actions/download-artifact@v2
        with:
          name: app-jar
          path: build/libs

      - name: 도커 허브 로그인
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: 도커 이미지 빌드
        run: docker build -t jaew0n/thiscoding:latest .

      - name: 도커 허브에 이미지 푸시
        run: docker push jaew0n/thiscoding:latest
